version: "3.8"

services:
    #KAFKA SERVICES
    zookeeper:
      image: confluentinc/cp-zookeeper:latest
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      expose:
        - 2181
    kafka:
      image: confluentinc/cp-kafka:5.3.1
      depends_on:
        - zookeeper
      expose:
        - 9092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      healthcheck:
        test: ["CMD", "nc", "-vz", "localhost", "9092"]
        interval: 10s
        timeout: 2s
        retries: 15
    
    #API
    api:
      build:
          context: ./api
          dockerfile: Dockerfile
      environment:
        KAFKA_SERVER_URL: kafka:9092
      expose:
        - 8000
      ports:
        - 8000:8000
      depends_on:
        kafka:
          condition: service_healthy
    
    # BACKEND SERVICES
    kitchen:
      build:
          context: ./services/kitchen
          dockerfile: Dockerfile
      environment:
        KAFKA_SERVER_URL: kafka:9092
      depends_on:
        kafka:
          condition: service_healthy
    announcement:
      build:
          context: ./services/announcement
          dockerfile: Dockerfile
      environment:
        KAFKA_SERVER_URL: kafka:9092
      depends_on:
        kafka:
          condition: service_healthy

